# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kuna/Github/bmsbelplus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kuna/Github/bmsbelplus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kuna/Github/bmsbelplus/CMakeFiles /home/kuna/Github/bmsbelplus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kuna/Github/bmsbelplus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bmsbel

# Build rule for target.
bmsbel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bmsbel
.PHONY : bmsbel

# fast build rule for target.
bmsbel/fast:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/build
.PHONY : bmsbel/fast

bmsbel/bms_bar.o: bmsbel/bms_bar.cpp.o
.PHONY : bmsbel/bms_bar.o

# target to build an object file
bmsbel/bms_bar.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_bar.cpp.o
.PHONY : bmsbel/bms_bar.cpp.o

bmsbel/bms_bar.i: bmsbel/bms_bar.cpp.i
.PHONY : bmsbel/bms_bar.i

# target to preprocess a source file
bmsbel/bms_bar.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_bar.cpp.i
.PHONY : bmsbel/bms_bar.cpp.i

bmsbel/bms_bar.s: bmsbel/bms_bar.cpp.s
.PHONY : bmsbel/bms_bar.s

# target to generate assembly for a file
bmsbel/bms_bar.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_bar.cpp.s
.PHONY : bmsbel/bms_bar.cpp.s

bmsbel/bms_bms.o: bmsbel/bms_bms.cpp.o
.PHONY : bmsbel/bms_bms.o

# target to build an object file
bmsbel/bms_bms.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_bms.cpp.o
.PHONY : bmsbel/bms_bms.cpp.o

bmsbel/bms_bms.i: bmsbel/bms_bms.cpp.i
.PHONY : bmsbel/bms_bms.i

# target to preprocess a source file
bmsbel/bms_bms.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_bms.cpp.i
.PHONY : bmsbel/bms_bms.cpp.i

bmsbel/bms_bms.s: bmsbel/bms_bms.cpp.s
.PHONY : bmsbel/bms_bms.s

# target to generate assembly for a file
bmsbel/bms_bms.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_bms.cpp.s
.PHONY : bmsbel/bms_bms.cpp.s

bmsbel/bms_buffer.o: bmsbel/bms_buffer.cpp.o
.PHONY : bmsbel/bms_buffer.o

# target to build an object file
bmsbel/bms_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_buffer.cpp.o
.PHONY : bmsbel/bms_buffer.cpp.o

bmsbel/bms_buffer.i: bmsbel/bms_buffer.cpp.i
.PHONY : bmsbel/bms_buffer.i

# target to preprocess a source file
bmsbel/bms_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_buffer.cpp.i
.PHONY : bmsbel/bms_buffer.cpp.i

bmsbel/bms_buffer.s: bmsbel/bms_buffer.cpp.s
.PHONY : bmsbel/bms_buffer.s

# target to generate assembly for a file
bmsbel/bms_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_buffer.cpp.s
.PHONY : bmsbel/bms_buffer.cpp.s

bmsbel/bms_channel.o: bmsbel/bms_channel.cpp.o
.PHONY : bmsbel/bms_channel.o

# target to build an object file
bmsbel/bms_channel.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_channel.cpp.o
.PHONY : bmsbel/bms_channel.cpp.o

bmsbel/bms_channel.i: bmsbel/bms_channel.cpp.i
.PHONY : bmsbel/bms_channel.i

# target to preprocess a source file
bmsbel/bms_channel.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_channel.cpp.i
.PHONY : bmsbel/bms_channel.cpp.i

bmsbel/bms_channel.s: bmsbel/bms_channel.cpp.s
.PHONY : bmsbel/bms_channel.s

# target to generate assembly for a file
bmsbel/bms_channel.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_channel.cpp.s
.PHONY : bmsbel/bms_channel.cpp.s

bmsbel/bms_exception.o: bmsbel/bms_exception.cpp.o
.PHONY : bmsbel/bms_exception.o

# target to build an object file
bmsbel/bms_exception.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_exception.cpp.o
.PHONY : bmsbel/bms_exception.cpp.o

bmsbel/bms_exception.i: bmsbel/bms_exception.cpp.i
.PHONY : bmsbel/bms_exception.i

# target to preprocess a source file
bmsbel/bms_exception.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_exception.cpp.i
.PHONY : bmsbel/bms_exception.cpp.i

bmsbel/bms_exception.s: bmsbel/bms_exception.cpp.s
.PHONY : bmsbel/bms_exception.s

# target to generate assembly for a file
bmsbel/bms_exception.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_exception.cpp.s
.PHONY : bmsbel/bms_exception.cpp.s

bmsbel/bms_header_table.o: bmsbel/bms_header_table.cpp.o
.PHONY : bmsbel/bms_header_table.o

# target to build an object file
bmsbel/bms_header_table.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_header_table.cpp.o
.PHONY : bmsbel/bms_header_table.cpp.o

bmsbel/bms_header_table.i: bmsbel/bms_header_table.cpp.i
.PHONY : bmsbel/bms_header_table.i

# target to preprocess a source file
bmsbel/bms_header_table.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_header_table.cpp.i
.PHONY : bmsbel/bms_header_table.cpp.i

bmsbel/bms_header_table.s: bmsbel/bms_header_table.cpp.s
.PHONY : bmsbel/bms_header_table.s

# target to generate assembly for a file
bmsbel/bms_header_table.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_header_table.cpp.s
.PHONY : bmsbel/bms_header_table.cpp.s

bmsbel/bms_note.o: bmsbel/bms_note.cpp.o
.PHONY : bmsbel/bms_note.o

# target to build an object file
bmsbel/bms_note.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_note.cpp.o
.PHONY : bmsbel/bms_note.cpp.o

bmsbel/bms_note.i: bmsbel/bms_note.cpp.i
.PHONY : bmsbel/bms_note.i

# target to preprocess a source file
bmsbel/bms_note.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_note.cpp.i
.PHONY : bmsbel/bms_note.cpp.i

bmsbel/bms_note.s: bmsbel/bms_note.cpp.s
.PHONY : bmsbel/bms_note.s

# target to generate assembly for a file
bmsbel/bms_note.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_note.cpp.s
.PHONY : bmsbel/bms_note.cpp.s

bmsbel/bms_parser.o: bmsbel/bms_parser.cpp.o
.PHONY : bmsbel/bms_parser.o

# target to build an object file
bmsbel/bms_parser.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_parser.cpp.o
.PHONY : bmsbel/bms_parser.cpp.o

bmsbel/bms_parser.i: bmsbel/bms_parser.cpp.i
.PHONY : bmsbel/bms_parser.i

# target to preprocess a source file
bmsbel/bms_parser.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_parser.cpp.i
.PHONY : bmsbel/bms_parser.cpp.i

bmsbel/bms_parser.s: bmsbel/bms_parser.cpp.s
.PHONY : bmsbel/bms_parser.s

# target to generate assembly for a file
bmsbel/bms_parser.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_parser.cpp.s
.PHONY : bmsbel/bms_parser.cpp.s

bmsbel/bms_regist_array.o: bmsbel/bms_regist_array.cpp.o
.PHONY : bmsbel/bms_regist_array.o

# target to build an object file
bmsbel/bms_regist_array.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_regist_array.cpp.o
.PHONY : bmsbel/bms_regist_array.cpp.o

bmsbel/bms_regist_array.i: bmsbel/bms_regist_array.cpp.i
.PHONY : bmsbel/bms_regist_array.i

# target to preprocess a source file
bmsbel/bms_regist_array.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_regist_array.cpp.i
.PHONY : bmsbel/bms_regist_array.cpp.i

bmsbel/bms_regist_array.s: bmsbel/bms_regist_array.cpp.s
.PHONY : bmsbel/bms_regist_array.s

# target to generate assembly for a file
bmsbel/bms_regist_array.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_regist_array.cpp.s
.PHONY : bmsbel/bms_regist_array.cpp.s

bmsbel/bms_text_file_reader.o: bmsbel/bms_text_file_reader.cpp.o
.PHONY : bmsbel/bms_text_file_reader.o

# target to build an object file
bmsbel/bms_text_file_reader.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_text_file_reader.cpp.o
.PHONY : bmsbel/bms_text_file_reader.cpp.o

bmsbel/bms_text_file_reader.i: bmsbel/bms_text_file_reader.cpp.i
.PHONY : bmsbel/bms_text_file_reader.i

# target to preprocess a source file
bmsbel/bms_text_file_reader.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_text_file_reader.cpp.i
.PHONY : bmsbel/bms_text_file_reader.cpp.i

bmsbel/bms_text_file_reader.s: bmsbel/bms_text_file_reader.cpp.s
.PHONY : bmsbel/bms_text_file_reader.s

# target to generate assembly for a file
bmsbel/bms_text_file_reader.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_text_file_reader.cpp.s
.PHONY : bmsbel/bms_text_file_reader.cpp.s

bmsbel/bms_time.o: bmsbel/bms_time.cpp.o
.PHONY : bmsbel/bms_time.o

# target to build an object file
bmsbel/bms_time.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_time.cpp.o
.PHONY : bmsbel/bms_time.cpp.o

bmsbel/bms_time.i: bmsbel/bms_time.cpp.i
.PHONY : bmsbel/bms_time.i

# target to preprocess a source file
bmsbel/bms_time.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_time.cpp.i
.PHONY : bmsbel/bms_time.cpp.i

bmsbel/bms_time.s: bmsbel/bms_time.cpp.s
.PHONY : bmsbel/bms_time.s

# target to generate assembly for a file
bmsbel/bms_time.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_time.cpp.s
.PHONY : bmsbel/bms_time.cpp.s

bmsbel/bms_util.o: bmsbel/bms_util.cpp.o
.PHONY : bmsbel/bms_util.o

# target to build an object file
bmsbel/bms_util.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_util.cpp.o
.PHONY : bmsbel/bms_util.cpp.o

bmsbel/bms_util.i: bmsbel/bms_util.cpp.i
.PHONY : bmsbel/bms_util.i

# target to preprocess a source file
bmsbel/bms_util.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_util.cpp.i
.PHONY : bmsbel/bms_util.cpp.i

bmsbel/bms_util.s: bmsbel/bms_util.cpp.s
.PHONY : bmsbel/bms_util.s

# target to generate assembly for a file
bmsbel/bms_util.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_util.cpp.s
.PHONY : bmsbel/bms_util.cpp.s

bmsbel/bms_word.o: bmsbel/bms_word.cpp.o
.PHONY : bmsbel/bms_word.o

# target to build an object file
bmsbel/bms_word.cpp.o:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_word.cpp.o
.PHONY : bmsbel/bms_word.cpp.o

bmsbel/bms_word.i: bmsbel/bms_word.cpp.i
.PHONY : bmsbel/bms_word.i

# target to preprocess a source file
bmsbel/bms_word.cpp.i:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_word.cpp.i
.PHONY : bmsbel/bms_word.cpp.i

bmsbel/bms_word.s: bmsbel/bms_word.cpp.s
.PHONY : bmsbel/bms_word.s

# target to generate assembly for a file
bmsbel/bms_word.cpp.s:
	$(MAKE) -f CMakeFiles/bmsbel.dir/build.make CMakeFiles/bmsbel.dir/bmsbel/bms_word.cpp.s
.PHONY : bmsbel/bms_word.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bmsbel"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bmsbel/bms_bar.o"
	@echo "... bmsbel/bms_bar.i"
	@echo "... bmsbel/bms_bar.s"
	@echo "... bmsbel/bms_bms.o"
	@echo "... bmsbel/bms_bms.i"
	@echo "... bmsbel/bms_bms.s"
	@echo "... bmsbel/bms_buffer.o"
	@echo "... bmsbel/bms_buffer.i"
	@echo "... bmsbel/bms_buffer.s"
	@echo "... bmsbel/bms_channel.o"
	@echo "... bmsbel/bms_channel.i"
	@echo "... bmsbel/bms_channel.s"
	@echo "... bmsbel/bms_exception.o"
	@echo "... bmsbel/bms_exception.i"
	@echo "... bmsbel/bms_exception.s"
	@echo "... bmsbel/bms_header_table.o"
	@echo "... bmsbel/bms_header_table.i"
	@echo "... bmsbel/bms_header_table.s"
	@echo "... bmsbel/bms_note.o"
	@echo "... bmsbel/bms_note.i"
	@echo "... bmsbel/bms_note.s"
	@echo "... bmsbel/bms_parser.o"
	@echo "... bmsbel/bms_parser.i"
	@echo "... bmsbel/bms_parser.s"
	@echo "... bmsbel/bms_regist_array.o"
	@echo "... bmsbel/bms_regist_array.i"
	@echo "... bmsbel/bms_regist_array.s"
	@echo "... bmsbel/bms_text_file_reader.o"
	@echo "... bmsbel/bms_text_file_reader.i"
	@echo "... bmsbel/bms_text_file_reader.s"
	@echo "... bmsbel/bms_time.o"
	@echo "... bmsbel/bms_time.i"
	@echo "... bmsbel/bms_time.s"
	@echo "... bmsbel/bms_util.o"
	@echo "... bmsbel/bms_util.i"
	@echo "... bmsbel/bms_util.s"
	@echo "... bmsbel/bms_word.o"
	@echo "... bmsbel/bms_word.i"
	@echo "... bmsbel/bms_word.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

